method: conv_onet
data:
  input_type: pointcloud
  classes: ['04379243', '02958343', '02691156']
  path: data/ShapeNet
  pointcloud_n: 300
  pointcloud_noise: 0.005
  points_subsample: 1024
  points_file: points.npz
  points_iou_file: points.npz
  voxels_file: null
  query_vol_size: 16
  unit_size: 0.1 
model:
  encoder: pointnet_local_pool
  encoder_kwargs:
    hidden_dim: 16
    plane_type: ['xz', 'xy', 'yz']
    plane_resolution: 32
    unet: True
    unet_kwargs:
      depth: 2
      merge_mode: concat
      start_filts: 16
    unet3d: False 
    local_coord: False
    pos_encoding: sin_cos
  decoder: simple_local
  decoder_kwargs:
    sample_mode: bilinear
    hidden_size: 8
    local_coord: False
    pos_encoding: sin_cos
  c_dim: 8
training:
  out_dir: out/pointcloud/PosEncoding/fully_shapenet_3plane_NoNorm
  batch_size: 8
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 10
  visualize_every: 10
  validate_every: 10
  checkpoint_every: 10
  backup_every: 10
  n_workers: 8
  n_workers_val: 4
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: model_best.pt
generation:
  vis_n_outputs: 2
  refine: false
  n_x: 128
  n_z: 1