method: conv_onet 
data:
  input_type: pointcloud
  classes: ['04379243', '02958343', '02691156']
  path: data/ShapeNet
  pointcloud_n: 3000
  pointcloud_noise: 0.005
  points_subsample: 2048
  points_file: points.npz
  points_iou_file: points.npz
  voxels_file: null
  query_vol_size: 32
  unit_size: 0.1
model:
  encoder: pointnet_local_pool
  encoder_kwargs:
    hidden_dim: 32
    plane_type: ['xz', 'xy', 'yz']
    plane_resolution: 64
    unet: true
    unet_kwargs:
      depth: 4
      merge_mode: concat
      start_filts: 32
    unet3d: false
  decoder: simple_local
  decoder_kwargs:
    sample_mode: bilinear
    hidden_size: 32
    local_coord: true
    pos_encoding: sin_cos
    use_siren: true
    w0: 30.0
  c_dim: 32
  embedding_mode: 'cat'
  # embedding_model: 'all-MiniLM-L12-v2'
  embedding_dim: 32
  num_classes: 3 
training:
  out_dir: out/pointcloud/merged_all_feature_nolm
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 100
  visualize_every: 1000
  validate_every: 2000
  checkpoint_every: 1000
  backup_every: 2000
  n_workers: 8
  n_workers_val: 4
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: model_best.pt
generation:
  vis_n_outputs: 2
  refine: false
  n_x: 128
  n_z: 1
